// <auto-generated />
namespace MyTelegram.Schema.Account;

/// <summary>
/// In-app web browser settings (layer 228+).
/// </summary>
[JsonDerivedType(typeof(TWebBrowserSettings), nameof(TWebBrowserSettings))]
[JsonDerivedType(typeof(TWebBrowserSettingsNotModified), nameof(TWebBrowserSettingsNotModified))]
public interface IWebBrowserSettings : IObject
{
}
