// <auto-generated />
namespace MyTelegram.Schema.Account;

[TlObject(0x9adf82fe)]
public sealed partial class RequestUpdateWebBrowserSettings : IRequest<MyTelegram.Schema.Account.IWebBrowserSettings>
{
    public uint ConstructorId => 0x9adf82fe;
    public int Flags { get; set; }
    public bool OpenExternalBrowser { get; set; }
    public bool DisplayCloseButton { get; set; }

    public void ComputeFlag()
    {
        if (OpenExternalBrowser) { Flags = Flags.SetBit(0); }
        if (DisplayCloseButton) { Flags = Flags.SetBit(1); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { OpenExternalBrowser = true; }
        if (Flags.IsBitSet(1)) { DisplayCloseButton = true; }
    }
}
