// <auto-generated />
namespace MyTelegram.Schema.Account;

[TlObject(0x56655768)]
public sealed partial class RequestGetWebBrowserSettings : IRequest<MyTelegram.Schema.Account.IWebBrowserSettings>
{
    public uint ConstructorId => 0x56655768;
    public long Hash { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Hash = buffer.ReadInt64();
    }
}
