// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="https://corefork.telegram.org/constructor/aiComposeToneExample" /></para>
/// </summary>
[TlObject(0xf1d628ec)]
public sealed partial class TAiComposeToneExample : IAiComposeToneExample
{
    public uint ConstructorId => 0xf1d628ec;
    public MyTelegram.Schema.ITextWithEntities From { get; set; }
    public MyTelegram.Schema.ITextWithEntities To { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(From);
        writer.Write(To);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        From = buffer.Read<MyTelegram.Schema.ITextWithEntities>();
        To = buffer.Read<MyTelegram.Schema.ITextWithEntities>();
    }
}
