// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="https://corefork.telegram.org/constructor/aiComposeTone" /></para>
/// </summary>
[TlObject(0xcff63ea9)]
public sealed partial class TAiComposeTone : IAiComposeTone
{
    public uint ConstructorId => 0xcff63ea9;
    public int Flags { get; set; }
    public bool Creator { get; set; }
    public long Id { get; set; }
    public long AccessHash { get; set; }
    public string Slug { get; set; }
    public string Title { get; set; }
    public long? EmojiId { get; set; }
    public string? Prompt { get; set; }
    public int? InstallsCount { get; set; }
    public long? AuthorId { get; set; }
    public MyTelegram.Schema.IAiComposeToneExample? ExampleEnglish { get; set; }

    public void ComputeFlag()
    {
        if (Creator) { Flags = Flags.SetBit(0); }
        if (/*EmojiId != 0 &&*/ EmojiId.HasValue) { Flags = Flags.SetBit(1); }
        if (/*InstallsCount != 0 && */InstallsCount.HasValue) { Flags = Flags.SetBit(2); }
        if (/*AuthorId != 0 &&*/ AuthorId.HasValue) { Flags = Flags.SetBit(3); }
        if (Prompt != null) { Flags = Flags.SetBit(4); }
        if (ExampleEnglish != null) { Flags = Flags.SetBit(5); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Id);
        writer.Write(AccessHash);
        writer.Write(Slug);
        writer.Write(Title);
        if (Flags.IsBitSet(1)) { writer.Write(EmojiId.Value); }
        if (Flags.IsBitSet(4)) { writer.Write(Prompt); }
        if (Flags.IsBitSet(2)) { writer.Write(InstallsCount.Value); }
        if (Flags.IsBitSet(3)) { writer.Write(AuthorId.Value); }
        if (Flags.IsBitSet(5)) { writer.Write(ExampleEnglish); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Creator = true; }
        Id = buffer.ReadInt64();
        AccessHash = buffer.ReadInt64();
        Slug = buffer.ReadString();
        Title = buffer.ReadString();
        if (Flags.IsBitSet(1)) { EmojiId = buffer.ReadInt64(); }
        if (Flags.IsBitSet(4)) { Prompt = buffer.ReadString(); }
        if (Flags.IsBitSet(2)) { InstallsCount = buffer.ReadInt32(); }
        if (Flags.IsBitSet(3)) { AuthorId = buffer.ReadInt64(); }
        if (Flags.IsBitSet(5)) { ExampleEnglish = buffer.Read<MyTelegram.Schema.IAiComposeToneExample>(); }
    }
}
