// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Describes a bot command that can be used in a chat
/// <para>See <a href="https://corefork.telegram.org/constructor/botCommand" /></para>
/// </summary>
[TlObject(0x9852d6d2)]
public sealed partial class TBotCommand : IBotCommand
{
    public uint ConstructorId => 0x9852d6d2;

    public int Flags { get; set; }

    /// <summary>
    /// Whether this command is for ephemeral messages (layer 228+).
    /// </summary>
    public bool Ephemeral { get; set; }

    /// <summary>
    /// <code>/command</code> name
    /// </summary>
    public string Command { get; set; }

    /// <summary>
    /// Description of the command
    /// </summary>
    public string Description { get; set; }

    public void ComputeFlag()
    {
        if (Ephemeral) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Command);
        writer.Write(Description);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Ephemeral = true; }
        Command = buffer.ReadString();
        Description = buffer.ReadString();
    }
}
