// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// Describes a bot command that can be used in a chat (layer 224 wire: no flags).
/// </summary>
[TlObject(0xc27ac8c7)]
public sealed partial class TBotCommand : IBotCommand
{
    public uint ConstructorId => 0xc27ac8c7;
    public string Command { get; set; }
    public string Description { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Command);
        writer.Write(Description);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Command = buffer.ReadString();
        Description = buffer.ReadString();
    }
}
