// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Contains info about a <a href="https://corefork.telegram.org/api/bots/connected-business-bots">connected business bot »</a>.
/// <para>See <a href="https://corefork.telegram.org/constructor/connectedBot" /></para>
/// </summary>
[TlObject(0x033ed001)]
public sealed partial class TConnectedBot : IConnectedBot
{
    public uint ConstructorId => 0x033ed001;
    public int Flags { get; set; }
    public long BotId { get; set; }
    public MyTelegram.Schema.IBusinessBotRecipients Recipients { get; set; }
    public MyTelegram.Schema.IBusinessBotRights Rights { get; set; }
    public string? Device { get; set; }
    public int? Date { get; set; }
    public string? Location { get; set; }

    public void ComputeFlag()
    {
        if (Device != null) { Flags = Flags.SetBit(0); }
        if (/*Date != 0 && */Date.HasValue) { Flags = Flags.SetBit(1); }
        if (Location != null) { Flags = Flags.SetBit(2); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(BotId);
        writer.Write(Recipients);
        writer.Write(Rights);
        if (Flags.IsBitSet(0)) { writer.Write(Device); }
        if (Flags.IsBitSet(1)) { writer.Write(Date.Value); }
        if (Flags.IsBitSet(2)) { writer.Write(Location); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        BotId = buffer.ReadInt64();
        Recipients = buffer.Read<MyTelegram.Schema.IBusinessBotRecipients>();
        Rights = buffer.Read<MyTelegram.Schema.IBusinessBotRights>();
        if (Flags.IsBitSet(0)) { Device = buffer.ReadString(); }
        if (Flags.IsBitSet(1)) { Date = buffer.ReadInt32(); }
        if (Flags.IsBitSet(2)) { Location = buffer.ReadString(); }
    }
}
