// <auto-generated />
namespace MyTelegram.Schema;

[TlObject(0x0773c080)]
public sealed partial class TInputAiComposeToneID : IInputAiComposeTone
{
    public uint ConstructorId => 0x0773c080;
    public long Id { get; set; }
    public long AccessHash { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Id);
        writer.Write(AccessHash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Id = buffer.ReadInt64();
        AccessHash = buffer.ReadInt64();
    }
}
