// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="https://corefork.telegram.org/constructor/inputRichFilePhoto" /></para>
/// </summary>
[TlObject(0x9b00622b)]
public sealed partial class TInputRichFilePhoto : IInputRichFile
{
    public uint ConstructorId => 0x9b00622b;
    public MyTelegram.Schema.IInputPhoto Id { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Id);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Id = buffer.Read<MyTelegram.Schema.IInputPhoto>();
    }
}
