// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="https://corefork.telegram.org/constructor/inputRichFileDocument" /></para>
/// </summary>
[TlObject(0x83281dbd)]
public sealed partial class TInputRichFileDocument : IInputRichFile
{
    public uint ConstructorId => 0x83281dbd;
    public MyTelegram.Schema.IInputDocument Id { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Id);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Id = buffer.Read<MyTelegram.Schema.IInputDocument>();
    }
}
