// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// Input rich message as page blocks (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/constructor/inputRichMessage" /></para>
/// </summary>
[TlObject(0xe4c449fc)]
public sealed partial class TInputRichMessage : IInputRichMessage
{
    public uint ConstructorId => 0xe4c449fc;
    public int Flags { get; set; }
    public bool Rtl { get; set; }
    public bool Noautolink { get; set; }
    public TVector<MyTelegram.Schema.IPageBlock> Blocks { get; set; }
    public TVector<MyTelegram.Schema.IInputPhoto>? Photos { get; set; }
    public TVector<MyTelegram.Schema.IInputDocument>? Documents { get; set; }
    public TVector<MyTelegram.Schema.IInputUser>? Users { get; set; }

    public void ComputeFlag()
    {
        if (Rtl) { Flags = Flags.SetBit(0); }
        if (Noautolink) { Flags = Flags.SetBit(1); }
        if (Photos?.Count > 0) { Flags = Flags.SetBit(2); }
        if (Documents?.Count > 0) { Flags = Flags.SetBit(3); }
        if (Users?.Count > 0) { Flags = Flags.SetBit(4); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Blocks);
        if (Flags.IsBitSet(2)) { writer.Write(Photos); }
        if (Flags.IsBitSet(3)) { writer.Write(Documents); }
        if (Flags.IsBitSet(4)) { writer.Write(Users); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Rtl = true; }
        if (Flags.IsBitSet(1)) { Noautolink = true; }
        Blocks = buffer.Read<TVector<MyTelegram.Schema.IPageBlock>>();
        if (Flags.IsBitSet(2)) { Photos = buffer.Read<TVector<MyTelegram.Schema.IInputPhoto>>(); }
        if (Flags.IsBitSet(3)) { Documents = buffer.Read<TVector<MyTelegram.Schema.IInputDocument>>(); }
        if (Flags.IsBitSet(4)) { Users = buffer.Read<TVector<MyTelegram.Schema.IInputUser>>(); }
    }
}
