// <auto-generated />
namespace MyTelegram.Schema;

[TlObject(0x0e0c35af)]
public sealed partial class TInputAiComposeToneSingleUse : IInputAiComposeTone
{
    public uint ConstructorId => 0x0e0c35af;
    public string CustomPrompt { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(CustomPrompt);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        CustomPrompt = buffer.ReadString();
    }
}
