// <auto-generated />
namespace MyTelegram.Schema;

[TlObject(0x1fa01357)]
public sealed partial class TInputAiComposeToneSlug : IInputAiComposeTone
{
    public uint ConstructorId => 0x1fa01357;
    public string Slug { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Slug);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Slug = buffer.ReadString();
    }
}
