// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// Input rich message as Markdown (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/constructor/inputRichMessageMarkdown" /></para>
/// </summary>
[TlObject(0x004b572c)]
public sealed partial class TInputRichMessageMarkdown : IInputRichMessage
{
    public uint ConstructorId => 0x004b572c;
    public int Flags { get; set; }
    public bool Rtl { get; set; }
    public bool Noautolink { get; set; }
    public string Markdown { get; set; }
    public TVector<MyTelegram.Schema.IInputRichFile>? Files { get; set; }

    public void ComputeFlag()
    {
        if (Rtl) { Flags = Flags.SetBit(0); }
        if (Noautolink) { Flags = Flags.SetBit(1); }
        if (Files?.Count > 0) { Flags = Flags.SetBit(2); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Markdown);
        if (Flags.IsBitSet(2)) { writer.Write(Files); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Rtl = true; }
        if (Flags.IsBitSet(1)) { Noautolink = true; }
        Markdown = buffer.ReadString();
        if (Flags.IsBitSet(2)) { Files = buffer.Read<TVector<MyTelegram.Schema.IInputRichFile>>(); }
    }
}
