// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// Rich message payload (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/constructor/richMessage" /></para>
/// </summary>
[TlObject(0xbaf39d8b)]
public sealed partial class TRichMessage : IRichMessage
{
    public uint ConstructorId => 0xbaf39d8b;
    public int Flags { get; set; }
    public bool Rtl { get; set; }
    public bool Part { get; set; }
    public TVector<MyTelegram.Schema.IPageBlock> Blocks { get; set; }
    public TVector<MyTelegram.Schema.IPhoto> Photos { get; set; }
    public TVector<MyTelegram.Schema.IDocument> Documents { get; set; }

    public void ComputeFlag()
    {
        if (Rtl) { Flags = Flags.SetBit(0); }
        if (Part) { Flags = Flags.SetBit(1); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Blocks);
        writer.Write(Photos);
        writer.Write(Documents);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Rtl = true; }
        if (Flags.IsBitSet(1)) { Part = true; }
        Blocks = buffer.Read<TVector<MyTelegram.Schema.IPageBlock>>();
        Photos = buffer.Read<TVector<MyTelegram.Schema.IPhoto>>();
        Documents = buffer.Read<TVector<MyTelegram.Schema.IDocument>>();
    }
}
