// <auto-generated />
namespace MyTelegram.Schema;

[TlObject(0x933ca597)]
public sealed partial class TWebDomainException : IWebDomainException
{
    public uint ConstructorId => 0x933ca597;
    public int Flags { get; set; }
    public string Domain { get; set; }
    public string Url { get; set; }
    public string Title { get; set; }
    public long? Favicon { get; set; }

    public void ComputeFlag()
    {
        if (/*Favicon != 0 &&*/ Favicon.HasValue) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Domain);
        writer.Write(Url);
        writer.Write(Title);
        if (Flags.IsBitSet(0)) { writer.Write(Favicon.Value); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        Domain = buffer.ReadString();
        Url = buffer.ReadString();
        Title = buffer.ReadString();
        if (Flags.IsBitSet(0)) { Favicon = buffer.ReadInt64(); }
    }
}
