// <auto-generated />
namespace MyTelegram.Schema.Messages;

/// <summary>
/// Fetch a message including its rich message body (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/method/messages.getRichMessage" /></para>
/// </summary>
[TlObject(0x501569cf)]
public sealed partial class RequestGetRichMessage : IRequest<MyTelegram.Schema.Messages.IMessages>
{
    public uint ConstructorId => 0x501569cf;
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public int Id { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(Id);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Peer = buffer.Read<MyTelegram.Schema.IInputPeer>();
        Id = buffer.ReadInt32();
    }
}
