// <auto-generated />
namespace MyTelegram.Schema.Messages;

/// <summary>
/// Successfully joined; carries the usual updates payload.
/// <para>See <a href="https://corefork.telegram.org/constructor/messages.chatInviteJoinResultOk" /></para>
/// </summary>
[TlObject(0x445663a7)]
public sealed partial class TChatInviteJoinResultOk : IChatInviteJoinResult
{
    public uint ConstructorId => 0x445663a7;
    public MyTelegram.Schema.IUpdates Updates { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Updates);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Updates = buffer.Read<MyTelegram.Schema.IUpdates>();
    }
}
