// <auto-generated />
namespace MyTelegram.Schema.Messages;

/// <summary>
/// Join requires a web-view flow (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/constructor/messages.chatInviteJoinResultWebView" /></para>
/// </summary>
[TlObject(0x61ca29d3)]
public sealed partial class TChatInviteJoinResultWebView : IChatInviteJoinResult
{
    public uint ConstructorId => 0x61ca29d3;
    public string Url { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Url);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Url = buffer.ReadString();
    }
}
