// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

/// <summary>
/// <para>See <a href="https://corefork.telegram.org/constructor/aicompose.tonesNotModified" /></para>
/// </summary>
[TlObject(0xc1f46103)]
public sealed partial class TTonesNotModified : ITones
{
    public uint ConstructorId => 0xc1f46103;

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
