// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

/// <summary>
/// <para>See <a href="https://corefork.telegram.org/constructor/aicompose.tones" /></para>
/// </summary>
[TlObject(0x6c9d0efe)]
public sealed partial class TTones : ITones
{
    public uint ConstructorId => 0x6c9d0efe;
    public long Hash { get; set; }
    public TVector<MyTelegram.Schema.IAiComposeTone> Tones { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Hash);
        writer.Write(Tones);
        writer.Write(Users);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Hash = buffer.ReadInt64();
        Tones = buffer.Read<TVector<MyTelegram.Schema.IAiComposeTone>>();
        Users = buffer.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}
