// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

[TlObject(0xd1b4ab14)]
public sealed partial class RequestGetToneExample : IRequest<MyTelegram.Schema.IAiComposeToneExample>
{
    public uint ConstructorId => 0xd1b4ab14;
    public MyTelegram.Schema.IInputAiComposeTone Tone { get; set; }
    public int Num { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Tone);
        writer.Write(Num);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Tone = buffer.Read<MyTelegram.Schema.IInputAiComposeTone>();
        Num = buffer.ReadInt32();
    }
}
