// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

/// <summary>
/// List AI compose tones (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/method/aicompose.getTones" /></para>
/// </summary>
[TlObject(0xabd59201)]
public sealed partial class RequestGetTones : IRequest<MyTelegram.Schema.Aicompose.ITones>
{
    public uint ConstructorId => 0xabd59201;
    public long Hash { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Hash = buffer.ReadInt64();
    }
}
