// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

[TlObject(0xdd39316a)]
public sealed partial class RequestDeleteTone : IRequest<IBool>
{
    public uint ConstructorId => 0xdd39316a;
    public MyTelegram.Schema.IInputAiComposeTone Tone { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Tone);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Tone = buffer.Read<MyTelegram.Schema.IInputAiComposeTone>();
    }
}
