// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

[TlObject(0xb2e8ba03)]
public sealed partial class RequestGetTone : IRequest<MyTelegram.Schema.Aicompose.ITones>
{
    public uint ConstructorId => 0xb2e8ba03;
    public MyTelegram.Schema.IInputAiComposeTone Tone { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Tone);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Tone = buffer.Read<MyTelegram.Schema.IInputAiComposeTone>();
    }
}
