// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

[TlObject(0x1782cbb1)]
public sealed partial class RequestSaveTone : IRequest<IBool>
{
    public uint ConstructorId => 0x1782cbb1;
    public MyTelegram.Schema.IInputAiComposeTone Tone { get; set; }
    public bool Unsave { get; set; }

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Tone);
        writer.Write(Unsave);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Tone = buffer.Read<MyTelegram.Schema.IInputAiComposeTone>();
        Unsave = buffer.ReadBoolean();
    }
}
