// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

[TlObject(0x903bcf59)]
public sealed partial class RequestUpdateTone : IRequest<MyTelegram.Schema.IAiComposeTone>
{
    public uint ConstructorId => 0x903bcf59;
    public int Flags { get; set; }
    public MyTelegram.Schema.IInputAiComposeTone Tone { get; set; }
    public bool? DisplayAuthor { get; set; }
    public long? EmojiId { get; set; }
    public string? Title { get; set; }
    public string? Prompt { get; set; }

    public void ComputeFlag()
    {
        if (DisplayAuthor.HasValue) { Flags = Flags.SetBit(0); }
        if (/*EmojiId != 0 &&*/ EmojiId.HasValue) { Flags = Flags.SetBit(1); }
        if (Title != null) { Flags = Flags.SetBit(2); }
        if (Prompt != null) { Flags = Flags.SetBit(3); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Tone);
        if (Flags.IsBitSet(0)) { writer.Write(DisplayAuthor.Value); }
        if (Flags.IsBitSet(1)) { writer.Write(EmojiId.Value); }
        if (Flags.IsBitSet(2)) { writer.Write(Title); }
        if (Flags.IsBitSet(3)) { writer.Write(Prompt); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        Tone = buffer.Read<MyTelegram.Schema.IInputAiComposeTone>();
        if (Flags.IsBitSet(0)) { DisplayAuthor = buffer.ReadBoolean(); }
        if (Flags.IsBitSet(1)) { EmojiId = buffer.ReadInt64(); }
        if (Flags.IsBitSet(2)) { Title = buffer.ReadString(); }
        if (Flags.IsBitSet(3)) { Prompt = buffer.ReadString(); }
    }
}
