// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

[TlObject(0x4aa83913)]
public sealed partial class RequestCreateTone : IRequest<MyTelegram.Schema.IAiComposeTone>
{
    public uint ConstructorId => 0x4aa83913;
    public int Flags { get; set; }
    public bool DisplayAuthor { get; set; }
    public long EmojiId { get; set; }
    public string Title { get; set; }
    public string Prompt { get; set; }

    public void ComputeFlag()
    {
        if (DisplayAuthor) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(EmojiId);
        writer.Write(Title);
        writer.Write(Prompt);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { DisplayAuthor = true; }
        EmojiId = buffer.ReadInt64();
        Title = buffer.ReadString();
        Prompt = buffer.ReadString();
    }
}
