// <auto-generated />
namespace MyTelegram.Schema.Account;

[TlObject(0xc31c8f4e)]
public sealed partial class TWebBrowserSettingsNotModified : IWebBrowserSettings
{
    public uint ConstructorId => 0xc31c8f4e;

    public void ComputeFlag() { }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
