// <auto-generated />
namespace MyTelegram.Schema.Account;

[TlObject(0x79eb8cb3)]
public sealed partial class TWebBrowserSettings : IWebBrowserSettings
{
    public uint ConstructorId => 0x79eb8cb3;
    public int Flags { get; set; }
    public bool OpenExternalBrowser { get; set; }
    public bool DisplayCloseButton { get; set; }
    public TVector<MyTelegram.Schema.IWebDomainException> ExternalExceptions { get; set; }
    public TVector<MyTelegram.Schema.IWebDomainException> InappExceptions { get; set; }
    public long Hash { get; set; }

    public void ComputeFlag()
    {
        if (OpenExternalBrowser) { Flags = Flags.SetBit(0); }
        if (DisplayCloseButton) { Flags = Flags.SetBit(1); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(ExternalExceptions);
        writer.Write(InappExceptions);
        writer.Write(Hash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { OpenExternalBrowser = true; }
        if (Flags.IsBitSet(1)) { DisplayCloseButton = true; }
        ExternalExceptions = buffer.Read<TVector<MyTelegram.Schema.IWebDomainException>>();
        InappExceptions = buffer.Read<TVector<MyTelegram.Schema.IWebDomainException>>();
        Hash = buffer.ReadInt64();
    }
}
