// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// AI compose tone (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/type/AiComposeTone" /></para>
/// </summary>
[JsonDerivedType(typeof(TAiComposeTone), nameof(TAiComposeTone))]
[JsonDerivedType(typeof(TAiComposeToneDefault), nameof(TAiComposeToneDefault))]
public interface IAiComposeTone : IObject
{
}
