// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// AI compose tone example (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/type/AiComposeToneExample" /></para>
/// </summary>
[JsonDerivedType(typeof(TAiComposeToneExample), nameof(TAiComposeToneExample))]
public interface IAiComposeToneExample : IObject
{
}
