// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// Layer 228 input rich message.
/// <para>See <a href="https://corefork.telegram.org/type/InputRichMessage" /></para>
/// </summary>
[JsonDerivedType(typeof(TInputRichMessage), nameof(TInputRichMessage))]
[JsonDerivedType(typeof(TInputRichMessageHTML), nameof(TInputRichMessageHTML))]
[JsonDerivedType(typeof(TInputRichMessageMarkdown), nameof(TInputRichMessageMarkdown))]
public interface IInputRichMessage : IObject
{
}
