// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// Input AI compose tone (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/type/InputAiComposeTone" /></para>
/// </summary>
[JsonDerivedType(typeof(TInputAiComposeToneDefault), nameof(TInputAiComposeToneDefault))]
[JsonDerivedType(typeof(TInputAiComposeToneID), nameof(TInputAiComposeToneID))]
[JsonDerivedType(typeof(TInputAiComposeToneSlug), nameof(TInputAiComposeToneSlug))]
[JsonDerivedType(typeof(TInputAiComposeToneSingleUse), nameof(TInputAiComposeToneSingleUse))]
public interface IInputAiComposeTone : IObject
{
}
