// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// Input file referenced by a rich message (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/type/InputRichFile" /></para>
/// </summary>
[JsonDerivedType(typeof(TInputRichFilePhoto), nameof(TInputRichFilePhoto))]
[JsonDerivedType(typeof(TInputRichFileDocument), nameof(TInputRichFileDocument))]
public interface IInputRichFile : IObject
{
}
