// <auto-generated />
namespace MyTelegram.Schema;

/// <summary>
/// Layer 228 rich message body (page blocks + media).
/// <para>See <a href="https://corefork.telegram.org/type/RichMessage" /></para>
/// </summary>
[JsonDerivedType(typeof(TRichMessage), nameof(TRichMessage))]
public interface IRichMessage : IObject
{
}
