// <auto-generated />
namespace MyTelegram.Schema.Aicompose;

/// <summary>
/// AI compose tone list (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/type/aicompose.Tones" /></para>
/// </summary>
[JsonDerivedType(typeof(TTones), nameof(TTones))]
[JsonDerivedType(typeof(TTonesNotModified), nameof(TTonesNotModified))]
public interface ITones : IObject
{
}
