// <auto-generated />
namespace MyTelegram.Schema.Messages;

/// <summary>
/// Result of joining a chat via invite / channel (layer 228+).
/// <para>See <a href="https://corefork.telegram.org/type/messages.ChatInviteJoinResult" /></para>
/// </summary>
[JsonDerivedType(typeof(TChatInviteJoinResultOk), nameof(TChatInviteJoinResultOk))]
[JsonDerivedType(typeof(TChatInviteJoinResultWebView), nameof(TChatInviteJoinResultWebView))]
public interface IChatInviteJoinResult : IObject
{
}
